### ISSUE TITLE
remove tesserae/text_access

### ISSUE THREAD

**Issue by nOkuda** [tesserae/tesserae-v5#21]
text_access directory is no longer used.

**Comment by dkstm95** [comment]
Hi :)
Can I fix this issue ?

**Comment by nOkuda** [comment]
@dkstm95 You are welcome to fix the issue.  Just remove the directory called text_access and make a pull request.

**Comment by jeffkinnison** [comment]
This should be handled by PR #27.

**Comment by nOkuda** [comment]
#25 did it.  Sorry for not closing earlier.
