### ISSUE TITLE
Filtering by language and author returns no hits

### ISSUE THREAD

**Issue by nOkuda** [tesserae/tesserae-v5#3]
I am running Ubuntu 18.04.1 LTS with [mongodb-org](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/) installed.  I imported the [demo documents in Jeff's fork](https://github.com/jeffkinnison/tesserae-v5/tree/master/demo) into my database and succeeded in receiving the expected results when querying without filters and with a filter only on the language.

When I attempted to query with a filter on both the language and the author, the database responded with empty lists.  I also attempted to query with a filter on language, author, and text (= CTS URN); this likewise resulted in an empty response.

Here's the relevant code:

```Python
import tesserae.db
import tesserae.text_access.storage

HOST = '127.0.0.1'
PORT = 27017
USER = None
PASSWORD = None
CLIENT = tesserae.db.get_connection(HOST, PORT, USER, PASSWORD)

language = 'latin'
author = None
# author = 'vergil'
title = None
db_response = tesserae.text_access.storage.retrieve_text_list(
    CLIENT, language=language, author=author, title=text)
print(db_response)
```

My guess is that there is [a bug in the way the filter combines restrictions](https://github.com/jeffkinnison/tesserae-v5/blob/90ba922f862005907248b28f443f2837c8b565aa/tesserae/db/mongodb.py#L170), but I am not experienced enough with mongodb to know whether my guess is correct.

**Comment by jeffkinnison** [comment]
Out of curiosity, which database are you using within MongoDB? If you were following the demo, the texts would be loaded into the `'tesstest'` database, but the default database accessed by `tesserarae.db.get_connection` is `'tesserae'`.

Have you tried passing 'tesstest' as the fifth argument to get_connection? Note, that database may also be empty if you have run the unit tests.

**Comment by jeffkinnison** [comment]
Okay, cool, I'll look into it.

**Comment by nOkuda** [comment]
My guess turned out to be correct.  [This line](https://github.com/jeffkinnison/tesserae-v5/blob/90ba922f862005907248b28f443f2837c8b565aa/tesserae/db/mongodb.py#L170) should be changed to:

```python
f = {'$and': [{k: v} for k, v in f.items()]}
```

(I would have made a pull request, but this main repo doesn't have that code yet.)

**Comment by jeffkinnison** [comment]
Thanks for looking into that. I'm working on unit tests for this specific problem anyway, so it's good to have a fix.

**Comment by nOkuda** [comment]
Commit 12fb5d48e4fa0046a529f5457ef24c02ffa83ec7 seems to have implemented the proposed solution.
