### ISSUE TITLE
Tokenization error on text ingestion

### ISSUE THREAD

**Issue by nOkuda** [tesserae/tesserae-v5#31]
https://github.com/tesserae/tesserae-v5/blob/c15efa46bed3dcc1bb7f7b0b4da38b34a59e6cb3/tesserae/tokenizers/base.py#L155

This line seems to be the beginning of the problem.  Based on my tests, `featurized` is a dictionary, not an array, so indexing by norm_i is throwing a key exception.  I'll let @jeffkinnison handle fixing this, since he probably has a better idea of what fixes would actually work.

**Comment by nOkuda** [comment]
Figured it out:  the `tokenize` method is broken, but sparse matrix matching uses the `tokenize2` method.  This issue should be closed once we're happy with sparse matrix matching and can remove aggregation matching; at the same time, I recommend removing the broken `tokenize` method and then renaming `tokenize2` to `tokenize`.

**Comment by jeffkinnison** [comment]
Yeah, I'm fixing this along with the unit testing. The fix should be posted here soon.
