### ISSUE TITLE
(software) feature request:  delete text

### ISSUE THREAD

**Issue by nOkuda** [tesserae/tesserae-v5#4]
I'd like a way to delete a document from the database.  I think this function would go in [`tesserae.text_access.storage`](https://github.com/jeffkinnison/tesserae-v5/blob/master/tesserae/text_access/storage.py).

**Comment by jeffkinnison** [comment]
Sure, I'll add this. I'm planning to rework the insert/query/update functions anyway because they're a bit dispersed at the moment and should all be moved into the `db` subpackage. Delete will be added when that update occurs.

**Comment by jeffkinnison** [comment]
This should be addressed by PR #8

**Comment by nOkuda** [comment]
Confirmed.
